# -*- coding: utf-8 -*-
"""컴프 조별과제(최연우)_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13v5OCmob1ui7vDrjisSqQqT0Xd6f0dt8
"""

class EmotionChainSystem:
    def __init__(self):
        self.current_emotion = None      # 현재 연속 중인 감정
        self.chain_count = 0             # 현재 체인 길이
        self.max_chain = 0               # 이번 게임 최고 체인 (기록용)

    def add_chain(self, emotion: str) -> int:
        """
        벽돌 파괴 시 호출되는 핵심 메서드
        Returns: 현재 체인 길이
        """
        if emotion == self.current_emotion:
            self.chain_count += 1
        else:
            # 감정 변경 → 체인 리셋
            self.current_emotion = emotion
            self.chain_count = 1

        # 최고 기록 갱신
        if self.chain_count > self.max_chain:
            self.max_chain = self.chain_count

        return self.chain_count

    def reset(self):
        """감정 폭발 후 또는 공이 떨어졌을 때 호출"""
        self.current_emotion = None
        self.chain_count = 0

    def get_multiplier(self) -> float:
        """체인 길이에 따른 점수 배율 계산 (기하급수적 증가)"""
        if self.chain_count <= 1:
            return 1.0
        # 체인이 길어질수록 배율이 강하게 증가
        return 1.0 + (self.chain_count ** 1.65) * 0.18
class ScoreManager:
    def __init__(self):
        self.total_score = 0
        self.base_scores = {
            "anger": 100,
            "joy": 60,
            "fear": 80,
            "surprise": 70
        }

    def calculate_score(self, emotion: str, chain_count: int, is_explosion=False) -> int:
        """
        핵심 점수 계산 함수
        - emotion: 파괴된 벽돌의 감정
        - chain_count: 현재 체인 길이
        - is_explosion: 감정 폭발로 인한 추가 파괴인지 여부
        """
        base = self.base_scores.get(emotion, 70)

        # 체인 배율 적용
        multiplier = 1.0
        if chain_count > 1:
            multiplier = 1.0 + (chain_count ** 1.65) * 0.18

        # 감정 폭발로 인한 추가 파괴는 보너스 추가
        if is_explosion:
            multiplier *= 1.4   # 폭발로 깬 벽돌은 40% 추가 점수

        final_score = int(base * multiplier)

        # 체인 길이에 따른 특별 보너스
        if chain_count >= 10:
            final_score += 300
        elif chain_count >= 7:
            final_score += 150
        elif chain_count >= 5:
            final_score += 80

        return final_score

    def add_score(self, points: int):
        self.total_score += points